apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "generador-publicidad.fullname" . }}-backend
  namespace: {{ include "generador-publicidad.namespace" . }}
  labels:
    {{- include "generador-publicidad.labels" . | nindent 4 }}
data:
  SPRING_PROFILES_ACTIVE: prod
  DB_HOST: {{ include "generador-publicidad.fullname" . }}-db
  DB_PORT: {{ .Values.postgresql.port | quote }}
  STORAGE_UPLOAD_DIR: /data/uploads
