apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "generador-publicidad.fullname" . }}-pgdata
  namespace: {{ include "generador-publicidad.namespace" . }}
  labels:
    {{- include "generador-publicidad.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.postgresql.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.postgresql.storage }}
