apiVersion: v1
kind: Service
metadata:
  name: {{ include "generador-publicidad.fullname" . }}-frontend
  namespace: {{ include "generador-publicidad.namespace" . }}
  labels:
    {{- include "generador-publicidad.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: http
      name: http
      protocol: TCP
  selector:
    {{- include "generador-publicidad.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
